// Generated by CoffeeScript 1.7.1
(function() {
  var express, mockUser, passport, passportMock;

  express = require('express');

  passport = require('passport');

  passportMock = require('./mock-passport-middleware');

  mockUser = {
    name: {
      username: 'TEST',
      password: 'TEST'
      // givenName: "Jonathon",
      // familyName: "Kresner"
    }
  };

  global.app = express();

  app.configure(function() {
    app.use(express["static"](__dirname + '/public'));
    app.use(express.bodyParser());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: 'your secret'
    }));
    app.use(passportMock.initialize(mockUser));
    return app.use(passport.session());
  });

}).call(this);
