
// Generated by CoffeeScript 1.7.1
(function() {
  var express, session, mockUser, passport, passportMock, cookieParser, bodyParser;

  express = require('express');
  session = require('express-session');

  // var LocalStrategy = require('passport-local').Strategy;
  passport = require('passport');
  // passport.use('local-login', new LocalStrategy({
  //     // by default, local strategy uses username and password
  //     usernameField : 'username',
  //     passwordField : 'password',
  //     passReqToCallback : true // allows us to pass back the entire request to the callback
  // },
  // function(req, username, password, done) { // callback with email and password from our form
  //     return login_auth_user(req, username, password, done, db);
  // }));

  passportMock = require('./mock-passport-middleware');
  cookieParser = require('cookie-parser');
  bodyParser = require('body-parser');


  mockUser = {
    username: 'TEST',
    password: 'TEST'
    
    // name: {
    //   // username: 'TEST',
    //   // password: 'TEST'
    //   givenName: "Jonathon",
    //   familyName: "Kresner"
    // }
  };

  global.app = express();

  // app.configure(function() {
    app.use(express["static"](__dirname + '/public'));
    app.use(session({ secret: 'keyboard cat' })); // session secret    
    
    var iniz = passportMock.initialize(mockUser);
    
    console.log("iniz");
    console.log(iniz);
    
    app.use(iniz);
    console.log("passport");
    console.log(passport);
    return app.use(passport.session());
  // });

}).call(this);

describe('Profile page functionality', function(){
  
  it('Text on profile page if logged in', function(done){
        request(app)
          .get('/users/profile')
          .expect(200)
          .end(function (err, res) {
            // console.log("===2===");
            // console.log(res);
            // console.log("===22===");
            // console.log("--- user1 ---");
            // console.log(res.user);
            // res.helpers.isLoggedIn();
            res.header.location.should.include('/users/profile');
            res.text.should.include('Profile Page');
            res.text.should.include('TEST');
            done();
          });
  });      
})