// var db = require('mysql2');


// public/json/metadata_*
// needs to be present for the web-app to work correctly
NODE_DATABASE = 'vamps_js_development'
// NODE_DATABASE = 'vamps_js_dev_av'
var db_config = {
  host: 'localhost',
  user: 'ruby',
  password: 'ruby',
  database: NODE_DATABASE
};


// Generated by LiveScript 1.2.0   https://github.com/felixge/node-mysql/issues/761
 // Edited: replaced all "db" with "exports.db"
 (function(){
   var handleDisconnect, this$ = this;
   mysql = require('mysql2');
   //config = require('./config');
   exports.db = null;
   handleDisconnect = function(){
     exports.db = mysql.createConnection(db_config);
     exports.db.connect(function(err){
       if (err != null) {
         console.log('Error connecting to mysql:', err);
         exports.db = null;
         return setTimeout(handleDisconnect, 2000);
       }
     });
     return exports.db.on('error', function(err){
       console.log('Database error:', err);
       if (err.code === 'PROTOCOL_CONNECTION_LOST') {
         exports.db = null;
         return handleDisconnect();
       } else {
         return process.exit(1);
       }
     });
   };
   handleDisconnect();
 }).call(this);