#!/bin/sh
#
# Runs the rdp classifier with a training set
# SMH 06/29/2007
#
#

############################################################
print_usage() {
    echo ""
    echo "This will classify taxonomy of 16s sequences of >200nt."
    echo ""
    echo "USAGE: $0 <infile> <outfile>"
	echo ""
    echo "<infile> is a file of fasta sequences"
    echo "<outfile> will contain the taxonomic assignments and boot strap values"
    echo ""
    echo ""
}
############################################################

if [ ! $1 ]; then
  print_usage;
  exit
fi

if [ ! $2 ]; then
  print_usage;
  exit
fi

INFILE="$1";
OUTFILE="$2";

if [ -z "$INFILE" ]; then
  print_usage;
  exit
fi

if [ ! -r $INFILE ]; then
    echo ""
    echo "Sorry, I can't open $INFILE"
    echo ""
fi

#PATH_2_JAVA="/bioware/jre/bin/java";
PATH_2_JAVA="java";
PATH_2_HERE=`dirname $0`
#PATH_2_HERE="/usr/local/www/vampsdev/docs/apps"

#java -Xmx2400m -jar /xraid/bioware/linuxOpteron/rdp_classifier/rdp_classifier-1.0.jar $1 $2  /xraid/bioware/linuxOpteron/rdp_classifier/train/rRNAClassifier.properties
#$PATH_2_JAVA -Xmx2400m -jar /usr/local/www/vampsdev/docs/apps/rdp_classifier-1.0.jar $1 $2  /usr/local/www/vampsdev/docs/apps/train3/rRNAClassifier.properties
#$PATH_2_JAVA -Xmx2400m -jar $PATH_2_HERE/rdp_classifier-1.0.jar $1 $2 $PATH_2_HERE/train_may08/rRNAClassifier.properties
#/usr/local/jdk/bin/java -Xmx2400m -jar $PATH_2_HERE/rdp_classifier-2.1.jar -q $1 -o $2 -t $PATH_2_HERE/train/rRNAClassifier.properties -f fixrank
#$PATH_2_JAVA -Xmx2400m -jar $PATH_2_HERE/rdp_classifier_2.1/rdp_classifier-2.1.jar -q $1 -o $2 -t $PATH_2_HERE/train/rRNAClassifier.properties -f fixrank
#$PATH_2_JAVA -Xmx2400m -jar $PATH_2_HERE/rdp_classifier_2.6/dist/classifier.jar -q $1 -o $2 -t $PATH_2_HERE/rdp_classifier_2.6/rRNAClassifier.properties -f fixrank
$PATH_2_JAVA -Xmx2400m -jar $PATH_2_HERE/rdp_classifier_2.6/dist/classifier.jar -q $1 -o $2 -t $PATH_2_HERE/train2014/rRNAClassifier.properties -f fixrank

