#!/usr/bin/env python
# -*- coding: utf-8

# Copyright (C) 2010 - 2012, A. Murat Eren
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.

import os
import sys




from Oligotyping_custom.utils.utils import import_error

try:
    from Oligotyping_custom.lib.oligotyping import Oligotyping
    from Oligotyping_custom.utils.utils import ConfigError
    from Oligotyping_custom.utils import parsers
except ImportError, e:
    import_error(e)
    sys.exit()


if __name__ == '__main__':
    if '--version' in sys.argv:
        print parsers.version
        sys.exit()

    parser = parsers.oligotyping()
    args = parser.parse_args()

    oligotyping = Oligotyping(args)

    try:
        oligotyping.run_all()
    except ConfigError, e:
        print e
        sys.exit(-1)
